export const FETCHING_CRYPTO_DATA  = '[FETCH GET] CRYPTO';
export const FETCHING_CRYPTO_DATA_SUCCESS  = '[FETCH GET SUCESS] CRYPTO';
export const FETCHING_CRYPTO_DATA_ERROR  = '[FETCH GET ERROR] CRYPTO';

